springfox:
  title: '@title@'
  version: '@version@'

fint:
  consumer:
    cache:
      disabled:
        dispensasjonautomatiskfredakulturminne: true
        tilskuddfartoy: true
        tilskuddfredahusprivateie: true
spring:
  mvc:
    logResolvedException: false
